name: DevTools
main: DevTools\DevTools
version: 1.13.2
api: [3.0.0, 3.5.1]
load: STARTUP
author: PocketMineTeam
commands:
 makeserver:
  usage: /makeserver
  permission: devtools.command.makeserver
 makeplugin:
  usage: /makeplugin (Plugin)
  permission: devtools.command.makeplugin
 checkperm:
  usage: /checkperm (Node) (Player)
  permission: devtools.command.checkperm;devtools.command.checkperm.other
permissions:
 devtools:
  default: true
  children:
   devtools.command:
    default: true
    children:
     devtools.command.makeplugin:
      default: true
     devtools.command.extractplugin:
      default: true
     devtools.command.makeserver:
      default: true
     devtools.command.checkperm:
      default: true
      children:
       devtools.command.checkperm.other:
        default: true
     devtools.command.genplugin:
      default: true
